# Playback Settings
loop-file=inf

# Video Settings
# profile=gpu-hq
# vo=gpu
# hwdec=auto-safe

# Audio Settings
volume=100
# volume-max=150

# Subtitles Settings
sub-auto=fuzzy
sub-font="sans-serif"
sub-font-size=40