#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --randomize ~/Pictures/Wallpapers/* & 
$HOME/.config/polybar/launch.sh & 
picom &
polybar &
dunst &
xset r rate 200 60

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5
bspc config top_padding          0
bcpc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true

bspc rule -a Gimp state=floating
bspc rule -a Emacs state=tiled
bspc rule -a discord state=tiled
bspc rule -a pavucontrol state=floating
bspc rule -a nm-connection-editor state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
