[colors]
background = #C917191a
background-alt = #373B41
foreground = #fff
primary = #00ff9f
secondary = #00ff9f
alert = #A54242
disabled = #707880

[bar/primarybar]
width = 100%
height = 20pt
radius = 1
dpi = 120

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

; border-size = 3pt
; border-top-size = 3pt
; border-left-size = 3pt
; border-right-size = 3pt

border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = Terminus:size=12;2
font-1 = Font Awesome 7 Free:pixelsize=12;2
font-2 = Font Awesome 7 Free Solid:pixelsize=12;2
font-3 = "Symbols Nerd Font Mono:size=12;3"
font-4 = Font Awesome 7 Brands:pixelsize=12;2

modules-left = xworkspaces xwindow
modules-right =  xkeyboard cpu memory wlan eth bluetooth pulseaudio backlight battery date
; modules-center = xworkspaces
; modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = %{F#00ff9f}<ramp-volume> %{F-}<label-volume>
label-volume = %percentage%%

label-muted =  muted
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#00ff9f}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#00ff9f} %ifname%%{F-} %local_ip%
; format-connected = <ramp-signal> <label-connected>
; format-disconnected = <label-disconnected>
; ramp-signal-0 = 
; ramp-signal-1 = 
; ramp-signal-2 = 
; ramp-signal-3 = 
; ramp-signal-4 = 
; ramp-signal-5 = 

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674} %ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %H:%M:%S

label = %date%
; label-foreground = ${colors.primary}

[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT0
adapter = AC0
poll-interval = 5
label =  %percentage:2%%

format-charging = %{F#00ff9f}<animation-charging> %{F-}<label-charging>
format-discharging = %{F#00ff9f}<ramp-capacity> %{F-}<label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%

label-full = %{F#00ff9f}
label-low = %{F#FF5733}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/bluetooth.sh
interval = 2
click-left = exec blueman
click-right = exec ~/.config/polybar/toggle_bluetooth.sh
format-padding = 1
format-background = #000000
format-foreground = #ffffff

[module/backlight]
type = internal/backlight

; Use `ls -1 /sys/class/backlight/` to find your device
card = intel_backlight
use-actual-brightness = true

; interval
poll-interval = 2

; Scroll to change brightness
enable-scroll = true

ramp-foreground = ${colors.primary}

; Available tags: <label> <ramp> <bar>
format = <ramp> <label>

; Only applies if <ramp> is used
ramp-0 = 
ramp-1 = 󰖨

; Label format
label = %percentage%%

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
